apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "Nginx Image 1.20 Version"
  labels:
    apps: web2
  name: web2
spec:
  replicas: 2
  selector:
    matchLabels:
      apps: web2
  template:
    metadata:
      labels:
        apps: web2
    spec:
      volumes:
        - name: dynamic-nfs-volume
          persistentVolumeClaim:
            claimName: nginx1
      initContainers:
        - name: webdata
          image: busybox
          command: ["/bin/sh","-c",'echo "<h1> Welcome To Kubernetes Demo </h1>" > /webdata/index.html']
          volumeMounts:
            - name: dynamic-nfs-volume
              mountPath: /webdata
      containers:
        - name: nginx
          image: nginx:latest
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m
          volumeMounts:
            - name: dynamic-nfs-volume
              mountPath: "/usr/share/nginx/html"
          ports:
            - containerPort: 80
