apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  annotations:
    kubernetes.io/change-cause: "Deploying Filebeat 7.15.0"
  labels:
    app: agent
    tier: backend
spec:
  selector:
    matchLabels:
      app: agent
      tier: backend
  template:
    metadata:
      labels:
        app: agent
        tier: backend
    spec:
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:7.15.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5044
