apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "Nginx Image 1.20 Version"
  labels:
    apps: nginx-webserver
  name: nginx-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: nginx-webserver
  template:
    metadata:
      labels:
        apps: nginx-webserver
    spec:
#      nodeSelector:
#        gitops: node1
      volumes:
        - name: emptydir
          emptyDir: {}
      initContainers:
        - name: webdata
          image: busybox
          command: ["/bin/sh","-c",'echo "<h1> Welcome To Kubernetes Demo </h1>" > /webdata/index.html']
          volumeMounts:
            - name: emptydir
              mountPath: /webdata
      containers:
        - name: nginx
          image: nginx:alpine
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m
          volumeMounts:
            - name: emptydir
              mountPath: "/usr/share/nginx/html"
          ports:
            - containerPort: 80
