apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath-demo
spec:
  storageClassName: local-storage-hostpath
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/kubernetes-volumes   ## Need to directory under /tmp ####
