apiVersion: v1
kind: Service
metadata:
  labels:
    apps: nginx-webserver
  name: svc1
spec:
  selector:
    apps: nginx-webserver
  type: LoadBalancer
  ports:
    - name: myport
      port: 80
      targetPort: 80

