apiVersion: v1
kind: Service
metadata:
  labels:
    apps: web2
  name: svc1
spec:
  selector:
    apps: web2
  type: NodePort
  ports:
    - name: myport
      port: 80
      targetPort: 80
      nodePort: 32324

